create table AUTHORITIES (authority varchar(255), userName varchar(255) not null, primary key (userName))
create table AulaAbierta (id bigint generated by default as identity (start with 1), fin date, inicio date, maxPlazas integer, curso_id integer, primary key (id))
create table Citacion (id bigint generated by default as identity (start with 1), acudio bit, cita date not null, hora varchar(6) not null, mujer_id bigint not null, servicio_id integer not null, primary key (id))
create table DocumentoAdjunto (id bigint generated by default as identity (start with 1), descripcion varchar(255), documento blob, tipo varchar(35) not null, ficha_id bigint, primary key (id))
create table Domicilio (id bigint generated by default as identity (start with 1), escalera varchar(255), letra char(255), nombreAvenida varchar(255), numero integer, piso integer, poblacion varchar(255), provincia_id integer, tipoDireccion_id integer, primary key (id))
create table Ficha (id bigint generated by default as identity (start with 1), apertura date, cerrada bit, cierre date, descripcion varchar(255), mujer_id bigint, servicio_id integer, primary key (id))
create table Horario (id integer generated by default as identity (start with 1), diaSemana integer, hora varchar(6), servicioId integer, servicio_id integer, primary key (id))
create table Mujer (id bigint generated by default as identity (start with 1), empadronada bit, fechaAlta timestamp, fechaNac timestamp, apellido1 varchar(30) not null, apellido2 varchar(30) not null, dni varchar(9) not null, nombre varchar(60) not null, telfFijo varchar(10), telfMovil varchar(10), domicilio_id bigint, primary key (id), unique (domicilio_id))
create table Mujer_AulaAbierta (personas_id bigint not null, talleres_id bigint not null)
create table Provincia (id integer generated by default as identity (start with 1), codigo varchar(2) not null, nombre varchar(30) not null, primary key (id), unique (codigo), unique (nombre))
create table Seguimiento (id bigint generated by default as identity (start with 1), fecha date, observaciones varchar(255), ficha_id bigint, primary key (id))
create table Servicio (id integer generated by default as identity (start with 1), codigo varchar(100) not null, descripcion varchar(100) not null, responsable_userName varchar(255) not null, primary key (id), unique (codigo), unique (responsable_userName))
create table Taller (id integer generated by default as identity (start with 1), codigo varchar(50) not null, taller varchar(100) not null, primary key (id), unique (codigo), unique (taller))
create table TipoDireccion (id integer generated by default as identity (start with 1), tipo varchar(50) not null, primary key (id), unique (tipo))
create table USERS (userName varchar(255) not null, enabled bit, password varchar(255), primary key (userName))
alter table AUTHORITIES add constraint FKAB62A701A1AE836A foreign key (userName) references USERS
alter table AulaAbierta add constraint FK787A2B39F27F9FA3 foreign key (curso_id) references Taller
alter table Citacion add constraint FKADD4B4B82FCEB561 foreign key (mujer_id) references Mujer
alter table Citacion add constraint FKADD4B4B838D77098 foreign key (servicio_id) references Servicio
alter table DocumentoAdjunto add constraint FK90C07EC7F26C7EAB foreign key (ficha_id) references Ficha
alter table Domicilio add constraint FKABA87945AEAC6718 foreign key (provincia_id) references Provincia
alter table Domicilio add constraint FKABA879456D1D3198 foreign key (tipoDireccion_id) references TipoDireccion
alter table Ficha add constraint FK40BA8D92FCEB561 foreign key (mujer_id) references Mujer
alter table Ficha add constraint FK40BA8D938D77098 foreign key (servicio_id) references Servicio
alter table Horario add constraint FKA49EDFC238D77098 foreign key (servicio_id) references Servicio
alter table Mujer add constraint FK473DBCF100EEC18 foreign key (domicilio_id) references Domicilio
alter table Mujer_AulaAbierta add constraint FK35DC26C9F3CD1C09 foreign key (personas_id) references Mujer
alter table Mujer_AulaAbierta add constraint FK35DC26C94966F8C0 foreign key (talleres_id) references AulaAbierta
alter table Seguimiento add constraint FK3AF78349F26C7EAB foreign key (ficha_id) references Ficha
alter table Servicio add constraint FK560F74F6ED7BAE8B foreign key (responsable_userName) references USERS